blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/Arinonia/orion-api/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/Arinonia/orion-api#readme
    about: Read the API documentation and examples
  - name: 🔗 Orion-Core Implementation
    url: https://github.com/Arinonia/orion-core
    about: Check the official implementation repository